apiVersion: v1
kind: Service
metadata:
  name: python-hello
  namespace: dev
spec:
  type: LoadBalancer
  selector:
    app: python-hello
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
