replicaCount: 3

image:
  repository: ujwal30/hello-flask
  tag: latest
  pullPolicy: Always

namespace:
  name: prod

container:
  port: 5000

service:
  type: LoadBalancer
  port: 80
  targetPort: 5000
